name: NekoBox-Inventories
version: '${project.version}'
main: es.nekobox.nekoboxinventories.Inventories
api-version: '1.20'
commands:
    findblock:
        description: Finds and teleports you to a specific block.
        usage: /findblock <block> <name>
    generatecode:
        description: Generates a linking code for the player.
        usage: /generatecode <name> <discord_name> <discord_id>
    loadinventory:
        description: Loads a player's inventory from the database.
        usage: /loadinventory <id>
#    spawnquestvillager:
#        description: Spawns the quest villager.
#        usage: /spawnquestvillager
    revive:
        description: Revive a player's inventory from their death records.
        usage: /revive <name>
    verifylink:
        description: Verifies a linking code for the player.
        usage: /verifylink <name> <discord_id> <code>